version: '3'
services:
  cache:
    image: redis
    container_name: cache
    expose:
      - 6379

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data3

volumes:
  pgdata:
  redis-data: